### ISSUE TITLE
Signer class potentially not producing a correct signature

### ISSUE THREAD

**Issue by jacob-tucker** [doublejumptokyo/fcl-kms-authorizer#19]
I have a repo set up where I am signing a simple message: "123456"

I am trying to use the Signer class to sign this message using the signUserMessage function, as shown here: https://github.com/jacob-tucker/emerald-id/blob/main/pages/api/sign.js#L93

I am then taking the message ("123456") and the produced signature and trying to verify it on my public key (the public key I got from doing signer.getPublicKey() ) here: https://github.com/jacob-tucker/emerald-id/blob/main/flow/cadence/scripts/verifyPublicKey.cdc

The method returns false though, so I suspect the signature isn't correct. Maybe it has something to do with the domain tag?

NOTE: This is the public key I'm using: `9a92119dd26b80cf9f4daf29340d68043d15685f0ac2c93203681b73960ffe9fa026efb9ba2f72a3f15884e849c4b7f8bf8fb086382488ffdcdf21c7e90560b7`

**Comment by avcdsld** [comment]
@jacob-tucker  Hi. I have found the cause of this failure.

The signature is being performed for the string `"123456"`, but the value being verified is a hexadecimal number `0x123456`.
https://github.com/jacob-tucker/emerald-id/blob/d0b85cdb3be675ffecbf38b0bc06b9a0bb22120d/flow/cadence/scripts/verifyPublicKey.cdc#L9

The correct `data` value is `313233343536`.
This value is obtained in js as follows
```js
Buffer.from("123456").toString('hex')
```

* Supplemental: The argument of `signUserSignature` is a string type.
