### ISSUE TITLE
Signing will fail if `keyIndex` argument of `authorize` does not match actual key index of the account on chain.

### ISSUE THREAD

**Issue by wphan** [doublejumptokyo/fcl-kms-authorizer#20]
This package assumes that the index of keyIds in an `authorizer` object matches the the index of the keys on chain.

If an account on chain has a mix of keys (both KMS using this package and non-KMS), it is not immediately obvious to the user why signing is failing, they will get the following error from a failed transaction:

```
[Error Code: 1006] invalid proposal key: public key 0 on account aaaaaaaaaaaaaaaa does not have a valid signature: [Error Code: 1009] invalid envelope key: public key 0 on account aaaaaaaaaaaaaaaa does not have a valid signature: signature is not valid
```

A possible workaround is by padding the keyIds of a new `authorizer` object to match the on chain key indices:
```
# there is an account 0xabc with 2 public keys: [0x000, 0x111], where only 0x111 is stored in KMS, and user wants to sign with 0x111
const authorizer = new KmsAuthorizer({ region: config.kmsRegion }, [config.kmsKeyIdFor0x111!, config.kmsKeyIdFor0x111!]);
authorization = await authorizer.authorize("0xabc", 1); // must use keyIndex 1 to sign with KMS key 0x111
```

It may help other users to document this in the README, or utilize 2 indices (1 for the on chain index, and another for the `keyId` index in `authorizer.authorizer()`)

**Comment by avcdsld** [comment]
@wphan  Thank you for creating the issue.
In fact, this is related to the history of the library interface, [which was extended backward-compatibly](https://github.com/doublejumptokyo/fcl-kms-authorizer/blob/92dfdc262170a4e0a4b2939522f79a68b19087a7/src/authorizer.ts#L29-L30) to accommodate multi-key in the middle of the process.

Referring to the current README, you can pass an array of keyIndexes as follows Could you try this to see if it works?

```js
const address = '01cf0e2f2f715450';
const keyIndexes = [1];
const authorization = authorizer.authorize(address, keyIndexes);
```

https://github.com/doublejumptokyo/fcl-kms-authorizer/blob/main/examples/send-tx.ts#L32-L34

**Comment by wphan** [comment]
there is an error in `signer` when i use `[1]` as the keyIndex:

```
Signatures ValidationException: 1 validation error detected: Value null at 'keyId' failed to satisfy constraint: Member must not be null
    at deserializeAws_json1_1SignCommandError (/api/node_modules/@aws-sdk/client-kms/dist-cjs/protocols/Aws_json1_1.js:2605:24)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at /api/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
    at /api/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
    at StandardRetryStrategy.retry (/api/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at /api/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
    at Signer._sign (/api/node_modules/fcl-kms-authorizer/src/signer.ts:96:22)
    at Signer.sign (/api/node_modules/fcl-kms-authorizer/src/signer.ts:18:27)
    at Object.signingFunction (/api/node_modules/fcl-kms-authorizer/src/authorizer.ts:44:26)
```

I think this is because [`Signer.sign()`](https://github.com/doublejumptokyo/fcl-kms-authorizer/blob/92dfdc262170a4e0a4b2939522f79a68b19087a7/src/signer.ts#L18) uses the same `keyIndex` value to look up a signing key

**Comment by avcdsld** [comment]
I see, I recognized the problem. Yes, this is indeed a problem.
Please wait while I figure out how to correct it as it should be.

**Comment by avcdsld** [comment]
@wphan I would like to make sure I have the use cases you need, can you tell me what key combinations and weights you want?

Is the following correct?

- Key0: non-KMS, weight 1000
- Key1: KMS, weight 1000

Or the following? This one is difficult to achieve with the current library.

- Key0: non-KMS, weight 500
- Key1: KMS, weight 500

**Comment by wphan** [comment]
i have the first case: all keys are weight 1000

**Comment by avcdsld** [comment]
@wphan Sorry for leaving this issue as it has been for so long.
The bug has now been fixed, along with an update to the latest version of the FCL.
Please try version `0.0.15`.
