### ISSUE TITLE
KMS signature length

### ISSUE THREAD

**Issue by jekel1818** [doublejumptokyo/fcl-kms-authorizer#8]
Most of the time, the `parseSignature` function will return a `Buffer` of length 32 for both `r` and `s`.

However, on some rare occasions, the length of either `r` or `s` will be 31. This will cause the signature length to be 126 instead of 128.

![kms-bug](https://user-images.githubusercontent.com/8727739/135159205-61de5815-cde2-4363-bd41-a065caea38a4.png)

After, since the length of the signature is 126, Flow fails to validate the signature. I did not tested a lot yet, but simply prepending 0 to the smaller Buffer ( or adding `00` to the hex output ) seems to fix the issue.

**Comment by avcdsld** [comment]
Thanks for reporting this.

It looks like this problem may occur when the byte sequence starts with leading zeros. Probably, there is a problem with this code `Buffer.concat([r, s])`.

I will investigate and test it.

**Comment by nvdtf** [comment]
For reference, check out the padding logic In `parseSignature` here https://github.com/onflow/flow-go-sdk/blob/921f824380fb3afd477eb86a2d15e10a4298fbc7/crypto/cloudkms/signer.go#L106

**Comment by avcdsld** [comment]
@tehranifar Thank you for the info!

@jekel1818 This problem has been fixed. Please try version 0.0.9. Thank you for reporting the issue!
